export default [
    {
        name: "Harry Potter and the Philosopher's Stone",
        price: 15.99,
        description: "Discover the magical world of Hogwarts as Harry Potter embarks on his first year at the famous wizarding school. Join him on his journey to uncover the mysteries of the Philosopher's Stone and confront the dark forces threatening the wizarding world.",
        ratings: 4.7,
        category: "Fantasy",
        seller: "Barnes & Noble",
        stock: 100,
        numOfReviews: 1500,
        isbn: "978-0-7475-3269-6",
        author: "J.K. Rowling"
    },
    {
        name: "To Kill a Mockingbird",
        price: 12.50,
        description: "Experience the powerful narrative of Scout Finch as she navigates through the complexities of race and morality in the Deep South during the Great Depression. Harper Lee's timeless classic explores themes of justice, compassion, and the loss of innocence.",
        ratings: 4.5,
        category: "Fiction",
        seller: "Waterstones",
        stock: 75,
        numOfReviews: 1200,
        isbn: "978-0-06-112008-4",
        author: "Harper Lee"
    },
    {
        name: "The Great Gatsby",
        price: 9.99,
        description: "Immerse yourself in the glitz and glamour of the Roaring Twenties with F. Scott Fitzgerald's masterpiece. Follow the enigmatic Jay Gatsby as he pursues his elusive American Dream, amidst the backdrop of wealth, love, and betrayal.",
        ratings: 4.3,
        category: "Literature",
        seller: "Amazon",
        stock: 50,
        numOfReviews: 800,
        isbn: "978-0-7432-7356-5",
        author: "F. Scott Fitzgerald"
    },
    {
        name: "1984",
        price: 11.25,
        description: "Enter the dystopian world of Big Brother and the Thought Police in George Orwell's chilling vision of a totalitarian society. In this cautionary tale, Winston Smith grapples with oppression, surveillance, and the loss of individual freedom.",
        ratings: 4.6,
        category: "Fiction",
        seller: "Books-A-Million",
        stock: 60,
        numOfReviews: 950,
        isbn: "978-0-452-28423-4",
        author: "George Orwell"
    },
    {
        name: "The Catcher in the Rye",
        price: 8.75,
        description: "Follow the rebellious Holden Caulfield as he embarks on a journey of self-discovery through the streets of New York City. J.D. Salinger's iconic novel explores themes of alienation, adolescence, and the search for authenticity.",
        ratings: 4.4,
        category: "Coming-of-Age",
        seller: "Book Depository",
        stock: 80,
        numOfReviews: 1100,
        isbn: "978-0-316-76948-0",
        author: "J.D. Salinger"
    },
    {
        name: "Pride and Prejudice",
        price: 10.50,
        description: "Delve into the world of Regency England with Jane Austen's beloved novel, where the spirited Elizabeth Bennet meets the enigmatic Mr. Darcy. Experience the timeless romance, wit, and social commentary that continue to captivate readers.",
        ratings: 4.8,
        category: "Romance",
        seller: "Barnes & Noble",
        stock: 90,
        numOfReviews: 1350,
        isbn: "978-0-14-143951-8",
        author: "Jane Austen"
    },
    {
        name: "The Lord of the Rings",
        price: 20.99,
        description: "Embark on an epic quest across Middle-earth with Frodo Baggins and his companions to destroy the One Ring and defeat the Dark Lord Sauron. J.R.R. Tolkien's timeless fantasy trilogy is a masterpiece of world-building, adventure, and heroism.",
        ratings: 4.9,
        category: "Fantasy",
        seller: "Waterstones",
        stock: 70,
        numOfReviews: 1700,
        isbn: "978-0-618-15396-1",
        author: "J.R.R. Tolkien"
    },
    {
        name: "Jane Eyre",
        price: 13.20,
        description: "Follow the journey of the independent and resilient Jane Eyre as she navigates through love, loss, and personal growth. Charlotte Brontë's classic novel is a compelling exploration of identity, morality, and the search for belonging.",
        ratings: 4.6,
        category: "Fiction",
        seller: "Amazon",
        stock: 55,
        numOfReviews: 900,
        isbn: "978-0-14-144114-6",
        author: "Charlotte Brontë"
    },
    {
        name: "The Hobbit",
        price: 14.99,
        description: "Join Bilbo Baggins as he embarks on a grand adventure to reclaim the lost Dwarf Kingdom of Erebor from the fearsome dragon Smaug. J.R.R. Tolkien's enchanting tale of courage, friendship, and discovery is a timeless classic for readers of all ages.",
        ratings: 4.7,
        category: "Literature",
        seller: "Books-A-Million",
        stock: 65,
        numOfReviews: 1000,
        isbn: "978-0-618-00221-4",
        author: "J.R.R. Tolkien"
    },
    {
        name: "Wuthering Heights",
        price: 11.99,
        description: "Enter the haunting world of Emily Brontë's masterpiece, where passion, revenge, and tragedy unfold on the windswept moors of Yorkshire. 'Wuthering Heights' is a dark and brooding tale of obsessive love and the destructive power of the human heart.",
        ratings: 4.5,
        category: "Romance",
        seller: "Book Depository",
        stock: 85,
        numOfReviews: 1250,
        isbn: "978-0-14-143955-6",
        author: "Emily Brontë"
    }
]
